name: 'Create UI Improvements Release'
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Version'
        required: true
env:
  NAME: 'UI Improvements'
  VERSION: ${{ github.event.inputs.version }}
  BASEPATH: './UI-Improvements/'
  ZIPPATHS: 'r6/'
  FILENAME: ${{ format('ui-improvements-{1}.zip', github.event.inputs.version) }}
jobs:
  build:
    name: 'Build Artifact'
    runs-on: ubuntu-latest
    steps:
      - name: 'Set ENV vars'
        run: echo "FILEPATH=$GITHUB_WORKSPACE/$FILENAME" >> $GITHUB_ENV

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Build artifact'
        run: |
          cd $BASEPATH
          zip -r $FILENAME $ZIPPATHS

      - name: 'Upload'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILEPATH }}

      - name: 'Create Release'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: ${{ env.NAME }} ${{ env.VERSION }}
          tag_name: ${{ format('v{0}', env.VERSION) }}
          files: ${{ env.FILEPATH }}
